name: CI - build & audit

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run npm audit (report only)
        run: |
          npm audit --omit=dev --audit-level=high || true

      # Snyk security scan (требует SNYK_TOKEN в secrets)
      # Установите токен: Settings → Secrets → Actions → New secret: SNYK_TOKEN
      # Получить токен: https://app.snyk.io/account
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # не блокируем пока, только мониторим
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Upload build artifacts (optional)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
