name: Build and Deploy Subgraph

# DISABLED AUTO-DEPLOY: only manual workflow_dispatch to save credits
on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Codegen
        working-directory: ./subgraph
        run: npx graph codegen
      - name: Build subgraph
        working-directory: ./subgraph
        run: npx graph build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Deploy subgraph (example)
        working-directory: ./subgraph
        env:
          GRAPH_ACCESS_TOKEN: ${{ secrets.GRAPH_ACCESS_TOKEN }}
        run: |
          # Example: publish to the Graph Hosted Service or Studio
          # You must set GRAPH_ACCESS_TOKEN in repo secrets and configure the subgraph name
          npx graph auth --access-token $GRAPH_ACCESS_TOKEN
          # npx graph deploy --studio <SUBGRAPH_NAME> --node https://api.thegraph.com/deploy/ 
          echo "Deploy step placeholder - configure with your subgraph name"
